# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cpuSchedulerGUI3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import csv
import test

class Ui_CPU_Scheduler(object):
    def setupUi(self, CPU_Scheduler):
        CPU_Scheduler.setObjectName("CPU_Scheduler")
        CPU_Scheduler.resize(826, 309)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CPU_Scheduler)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetOutput = QtWidgets.QWidget(CPU_Scheduler)
        self.widgetOutput.setMinimumSize(QtCore.QSize(401, 291))
        self.widgetOutput.setObjectName("widgetOutput")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetOutput)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.widgetOutput)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 2, 7, 1)
        self.processInput = QtWidgets.QTextEdit(self.widgetOutput)
        self.processInput.setMinimumSize(QtCore.QSize(131, 31))
        self.processInput.setMaximumSize(QtCore.QSize(131, 31))
        self.processInput.setObjectName("processInput")
        self.gridLayout_2.addWidget(self.processInput, 0, 0, 1, 2)
        self.output1 = QtWidgets.QTextBrowser(self.widgetOutput)
        self.output1.setMinimumSize(QtCore.QSize(111, 131))
        self.output1.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.output1.setObjectName("output1")
        self.gridLayout_2.addWidget(self.output1, 0, 3, 2, 1)
        self.output2 = QtWidgets.QTextBrowser(self.widgetOutput)
        self.output2.setMinimumSize(QtCore.QSize(111, 131))
        self.output2.setObjectName("output2")
        self.gridLayout_2.addWidget(self.output2, 0, 4, 2, 1)
        self.coreCount_lbl = QtWidgets.QLabel(self.widgetOutput)
        self.coreCount_lbl.setObjectName("coreCount_lbl")
        self.gridLayout_2.addWidget(self.coreCount_lbl, 2, 0, 1, 1)
        self.output3 = QtWidgets.QTextBrowser(self.widgetOutput)
        self.output3.setMinimumSize(QtCore.QSize(111, 131))
        self.output3.setObjectName("output3")
        self.gridLayout_2.addWidget(self.output3, 2, 3, 5, 1)
        self.output4 = QtWidgets.QTextBrowser(self.widgetOutput)
        self.output4.setMinimumSize(QtCore.QSize(111, 131))
        self.output4.setObjectName("output4")
        self.gridLayout_2.addWidget(self.output4, 2, 4, 5, 1)
        self.coreCount = QtWidgets.QSpinBox(self.widgetOutput)
        self.coreCount.setMinimum(0)
        self.coreCount.setMaximum(99)
        self.coreCount.setProperty("value", 4)
        self.coreCount.setObjectName("coreCount")
        self.gridLayout_2.addWidget(self.coreCount, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widgetOutput)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 4, 0, 1, 2)
        self.queues = QtWidgets.QSpinBox(self.widgetOutput)
        self.queues.setProperty("value", 1)
        self.queues.setObjectName("queues")
        self.gridLayout_2.addWidget(self.queues, 3, 1, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.widgetOutput)
        self.run_btn.setMinimumSize(QtCore.QSize(131, 31))
        self.run_btn.setObjectName("run_btn")
        self.gridLayout_2.addWidget(self.run_btn, 5, 0, 1, 2)
        self.queues_lbl = QtWidgets.QLabel(self.widgetOutput)
        self.queues_lbl.setObjectName("queues_lbl")
        self.gridLayout_2.addWidget(self.queues_lbl, 3, 0, 1, 1)
        self.stop_btn = QtWidgets.QPushButton(self.widgetOutput)
        self.stop_btn.setMinimumSize(QtCore.QSize(131, 31))
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout_2.addWidget(self.stop_btn, 6, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.widgetOutput)
        self.tabWidget.setMaximumSize(QtCore.QSize(131, 81))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.algorithm1tab = QtWidgets.QWidget()
        self.algorithm1tab.setObjectName("algorithm1tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.algorithm1tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.algorithm1 = QtWidgets.QComboBox(self.algorithm1tab)
        self.algorithm1.setObjectName("algorithm1")
        self.algorithm1.addItem("")
        self.algorithm1.addItem("")
        self.algorithm1.addItem("")
        self.algorithm1.addItem("")
        self.algorithm1.addItem("")
        self.algorithm1.addItem("")
        self.verticalLayout_7.addWidget(self.algorithm1)
        self.RRTimeQ1 = QtWidgets.QSpinBox(self.algorithm1tab)
        self.RRTimeQ1.setObjectName("RRTimeQ1")
        self.verticalLayout_7.addWidget(self.RRTimeQ1)
        self.tabWidget.addTab(self.algorithm1tab, "")
        self.algorithm2tab = QtWidgets.QWidget()
        self.algorithm2tab.setObjectName("algorithm2tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.algorithm2tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.algorithm2 = QtWidgets.QComboBox(self.algorithm2tab)
        self.algorithm2.setObjectName("algorithm2")
        self.algorithm2.addItem("")
        self.algorithm2.addItem("")
        self.algorithm2.addItem("")
        self.algorithm2.addItem("")
        self.algorithm2.addItem("")
        self.algorithm2.addItem("")
        self.verticalLayout_8.addWidget(self.algorithm2)
        self.RRTimeQ2 = QtWidgets.QSpinBox(self.algorithm2tab)
        self.RRTimeQ2.setObjectName("RRTimeQ2")
        self.verticalLayout_8.addWidget(self.RRTimeQ2)
        self.tabWidget.addTab(self.algorithm2tab, "")
        self.algorithm3tab = QtWidgets.QWidget()
        self.algorithm3tab.setObjectName("algorithm3tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.algorithm3tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.algorithm3 = QtWidgets.QComboBox(self.algorithm3tab)
        self.algorithm3.setObjectName("algorithm3")
        self.algorithm3.addItem("")
        self.algorithm3.addItem("")
        self.algorithm3.addItem("")
        self.algorithm3.addItem("")
        self.algorithm3.addItem("")
        self.algorithm3.addItem("")
        self.verticalLayout_6.addWidget(self.algorithm3)
        self.RRTimeQ3 = QtWidgets.QSpinBox(self.algorithm3tab)
        self.RRTimeQ3.setObjectName("RRTimeQ3")
        self.verticalLayout_6.addWidget(self.RRTimeQ3)
        self.tabWidget.addTab(self.algorithm3tab, "")
        self.algorithm4tab = QtWidgets.QWidget()
        self.algorithm4tab.setObjectName("algorithm4tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.algorithm4tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.algorithm4 = QtWidgets.QComboBox(self.algorithm4tab)
        self.algorithm4.setObjectName("algorithm4")
        self.algorithm4.addItem("")
        self.algorithm4.addItem("")
        self.algorithm4.addItem("")
        self.algorithm4.addItem("")
        self.algorithm4.addItem("")
        self.algorithm4.addItem("")
        self.verticalLayout_5.addWidget(self.algorithm4)
        self.RRTimeQ4 = QtWidgets.QSpinBox(self.algorithm4tab)
        self.RRTimeQ4.setObjectName("RRTimeQ4")
        self.verticalLayout_5.addWidget(self.RRTimeQ4)
        self.tabWidget.addTab(self.algorithm4tab, "")
        self.algorithm5tab = QtWidgets.QWidget()
        self.algorithm5tab.setObjectName("algorithm5tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.algorithm5tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.algorithm5 = QtWidgets.QComboBox(self.algorithm5tab)
        self.algorithm5.setObjectName("algorithm5")
        self.algorithm5.addItem("")
        self.algorithm5.addItem("")
        self.algorithm5.addItem("")
        self.algorithm5.addItem("")
        self.algorithm5.addItem("")
        self.algorithm5.addItem("")
        self.verticalLayout_4.addWidget(self.algorithm5)
        self.RRTimeQ5 = QtWidgets.QSpinBox(self.algorithm5tab)
        self.RRTimeQ5.setObjectName("RRTimeQ5")
        self.verticalLayout_4.addWidget(self.RRTimeQ5)
        self.tabWidget.addTab(self.algorithm5tab, "")
        self.algorithm6tab = QtWidgets.QWidget()
        self.algorithm6tab.setObjectName("algorithm6tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.algorithm6tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.algorithm6 = QtWidgets.QComboBox(self.algorithm6tab)
        self.algorithm6.setObjectName("algorithm6")
        self.algorithm6.addItem("")
        self.algorithm6.addItem("")
        self.algorithm6.addItem("")
        self.algorithm6.addItem("")
        self.algorithm6.addItem("")
        self.algorithm6.addItem("")
        self.verticalLayout_3.addWidget(self.algorithm6)
        self.RRTimeQ6 = QtWidgets.QSpinBox(self.algorithm6tab)
        self.RRTimeQ6.setObjectName("RRTimeQ6")
        self.verticalLayout_3.addWidget(self.RRTimeQ6)
        self.tabWidget.addTab(self.algorithm6tab, "")
        self.algorithm7tab = QtWidgets.QWidget()
        self.algorithm7tab.setObjectName("algorithm7tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.algorithm7tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.algorithm7 = QtWidgets.QComboBox(self.algorithm7tab)
        self.algorithm7.setObjectName("algorithm7")
        self.algorithm7.addItem("")
        self.algorithm7.addItem("")
        self.algorithm7.addItem("")
        self.algorithm7.addItem("")
        self.algorithm7.addItem("")
        self.algorithm7.addItem("")
        self.verticalLayout_2.addWidget(self.algorithm7)
        self.RRTimeQ7 = QtWidgets.QSpinBox(self.algorithm7tab)
        self.RRTimeQ7.setObjectName("RRTimeQ7")
        self.verticalLayout_2.addWidget(self.RRTimeQ7)
        self.tabWidget.addTab(self.algorithm7tab, "")
        self.algorithm8tab = QtWidgets.QWidget()
        self.algorithm8tab.setObjectName("algorithm8tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.algorithm8tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.algorithm8 = QtWidgets.QComboBox(self.algorithm8tab)
        self.algorithm8.setObjectName("algorithm8")
        self.algorithm8.addItem("")
        self.algorithm8.addItem("")
        self.algorithm8.addItem("")
        self.algorithm8.addItem("")
        self.algorithm8.addItem("")
        self.algorithm8.addItem("")
        self.verticalLayout.addWidget(self.algorithm8)
        self.RRTimeQ8 = QtWidgets.QSpinBox(self.algorithm8tab)
        self.RRTimeQ8.setObjectName("RRTimeQ8")
        self.verticalLayout.addWidget(self.RRTimeQ8)
        self.tabWidget.addTab(self.algorithm8tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widgetOutput)
        self.widget = QtWidgets.QWidget(CPU_Scheduler)
        self.widget.setMinimumSize(QtCore.QSize(401, 291))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.graphicsView.setMinimumSize(QtCore.QSize(379, 269))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.widget.raise_()
        self.widgetOutput.raise_()

        self.retranslateUi(CPU_Scheduler)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CPU_Scheduler)

    def retranslateUi(self, CPU_Scheduler):
        _translate = QtCore.QCoreApplication.translate
        CPU_Scheduler.setWindowTitle(_translate("CPU_Scheduler", "Form"))
        self.processInput.setHtml(_translate("CPU_Scheduler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.processInput.setPlaceholderText(_translate("CPU_Scheduler", "process input .csv"))
        self.output1.setHtml(_translate("CPU_Scheduler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.output1.setPlaceholderText(_translate("CPU_Scheduler", "Sample Output Box 1"))
        self.output2.setHtml(_translate("CPU_Scheduler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.output2.setPlaceholderText(_translate("CPU_Scheduler", "Sample Output Box 2"))
        self.coreCount_lbl.setText(_translate("CPU_Scheduler", "Core Count"))
        self.output3.setHtml(_translate("CPU_Scheduler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.output3.setPlaceholderText(_translate("CPU_Scheduler", "Sample Output Box 3"))
        self.output4.setHtml(_translate("CPU_Scheduler", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.output4.setPlaceholderText(_translate("CPU_Scheduler", "Sample Output Box 4"))
        self.coreCount.setWhatsThis(_translate("CPU_Scheduler", "<html><head/><body><p>coreCount</p></body></html>"))
        self.run_btn.setText(_translate("CPU_Scheduler", "Run"))
        self.queues_lbl.setText(_translate("CPU_Scheduler", "Queues"))
        self.stop_btn.setText(_translate("CPU_Scheduler", "Stop"))
        self.algorithm1.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm1.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm1.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm1.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm1.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm1.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm1tab), _translate("CPU_Scheduler", "Algorithm 1"))
        self.algorithm2.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm2.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm2.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm2.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm2.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm2.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm2tab), _translate("CPU_Scheduler", "Algorithm 2"))
        self.algorithm3.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm3.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm3.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm3.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm3.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm3.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm3tab), _translate("CPU_Scheduler", "Algorithm 3"))
        self.algorithm4.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm4.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm4.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm4.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm4.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm4.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm4tab), _translate("CPU_Scheduler", "Algorithm 4"))
        self.algorithm5.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm5.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm5.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm5.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm5.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm5.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm5tab), _translate("CPU_Scheduler", "Algorithm 5"))
        self.algorithm6.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm6.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm6.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm6.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm6.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm6.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm6tab), _translate("CPU_Scheduler", "Algorithm 6"))
        self.algorithm7.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm7.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm7.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm7.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm7.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm7.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm7tab), _translate("CPU_Scheduler", "Algorithm 7"))
        self.algorithm8.setItemText(0, _translate("CPU_Scheduler", "None"))
        self.algorithm8.setItemText(1, _translate("CPU_Scheduler", "FCFS"))
        self.algorithm8.setItemText(2, _translate("CPU_Scheduler", "RR"))
        self.algorithm8.setItemText(3, _translate("CPU_Scheduler", "SPN"))
        self.algorithm8.setItemText(4, _translate("CPU_Scheduler", "SRT"))
        self.algorithm8.setItemText(5, _translate("CPU_Scheduler", "HRRN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm8tab), _translate("CPU_Scheduler", "Algorithm 8"))


        self.run_btn.clicked.connect(self.run_btn_clicked)
        self.stop_btn.clicked.connect(self.stop_btn_clicked)

    def run_btn_clicked(self):
        def variables(coreCount, queueCount, algorithm1, algorithm2, algorithm3, algorithm4, algorithm5, algorithm6, algorithm7, algorithm8, RRTimeQ1, RRTimeQ2, RRTimeQ3, RRTimeQ4, RRTimeQ5, RRTimeQ6, RRTimeQ7, RRTimeQ8):
            test.someFunction(coreCount, queueCount, algorithm1, algorithm2, algorithm3, algorithm4, algorithm5, algorithm6, algorithm7, algorithm8, RRTimeQ1, RRTimeQ2, RRTimeQ3, RRTimeQ4, RRTimeQ5, RRTimeQ6, RRTimeQ7, RRTimeQ8)
        coreCount = self.coreCount.value()
        queueCount = self.queues.value()
        RRTimeQ1 = self.RRTimeQ1.value()
        RRTimeQ2 = self.RRTimeQ2.value()
        RRTimeQ3 = self.RRTimeQ3.value()
        RRTimeQ4 = self.RRTimeQ4.value()
        RRTimeQ5 = self.RRTimeQ5.value()
        RRTimeQ6 = self.RRTimeQ6.value()
        RRTimeQ7 = self.RRTimeQ7.value()
        RRTimeQ8 = self.RRTimeQ8.value()
        algorithm1 = str(self.algorithm1.currentText())
        algorithm2 = str(self.algorithm2.currentText())
        algorithm3 = str(self.algorithm3.currentText())
        algorithm4 = str(self.algorithm4.currentText())
        algorithm5 = str(self.algorithm5.currentText())
        algorithm6 = str(self.algorithm6.currentText())
        algorithm7 = str(self.algorithm7.currentText())
        algorithm8 = str(self.algorithm8.currentText())
        processInputLocation = self.processInput.toPlainText()
        processInputLocation = processInputLocation.replace('file:///', '')
        with open(processInputLocation) as f:
             reader = csv.reader(f)
        variables(coreCount, queueCount, algorithm1, algorithm2, algorithm3, algorithm4, algorithm5, algorithm6, algorithm7, algorithm8, RRTimeQ1, RRTimeQ2, RRTimeQ3, RRTimeQ4, RRTimeQ5, RRTimeQ6, RRTimeQ7, RRTimeQ8)

        #     #for row in reader:
        #         #self.output1.append(str(row))
        #         #print(type(row))
        #     self.output1.append(str(test.someFunction(reader)))
    def stop_btn_clicked(self):
        self.output1.append("stop clicked")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_CPU_Scheduler()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())