import cpuSchedulerGUI4

def someFunction(self, reader, coreCount, queueCount, algorithm1, algorithm2, algorithm3, algorithm4, algorithm5, algorithm6, algorithm7, algorithm8, RRTimeQ1, RRTimeQ2, RRTimeQ3, RRTimeQ4, RRTimeQ5, RRTimeQ6, RRTimeQ7, RRTimeQ8):
	cpuSchedulerGUI4.output(self, coreCount)
	cpuSchedulerGUI4.output(self, queueCount)
	cpuSchedulerGUI4.output(self, algorithm1)
	cpuSchedulerGUI4.output(self, algorithm2)
	cpuSchedulerGUI4.output(self, algorithm3)
	cpuSchedulerGUI4.output(self, algorithm4)
	cpuSchedulerGUI4.output(self, algorithm5)
	cpuSchedulerGUI4.output(self, algorithm6)
	cpuSchedulerGUI4.output(self, algorithm7)
	cpuSchedulerGUI4.output(self, algorithm8)
	cpuSchedulerGUI4.output(self, RRTimeQ1)
	cpuSchedulerGUI4.output(self, RRTimeQ2)
	cpuSchedulerGUI4.output(self, RRTimeQ3)
	cpuSchedulerGUI4.output(self, RRTimeQ4)
	cpuSchedulerGUI4.output(self, RRTimeQ5)
	cpuSchedulerGUI4.output(self, RRTimeQ6)
	cpuSchedulerGUI4.output(self, RRTimeQ7)
	cpuSchedulerGUI4.output(self, RRTimeQ8)